### ISSUE TITLE
What is the difference between /initiate and /connect

### ISSUE THREAD

**Issue by arnaudambro** [Fintecture/fintecture-sdk-javascript#12]
I try to understand here and in your documentation, but I have a hard time...

What is the difference between both ? When should I use teach of them ?

**Comment by hugofintecture** [comment]
Hello @arnaudambro! Really sorry for this long delay.
The initiate endpoint permit to process a payment without an user interface while the connect endpoint present an interface to let the user choose his bank and process the payment.

**Comment by arnaudambro** [comment]
thanks for you reply

It would be great to have a little more documented SDK !
The differences between https://github.com/Fintecture/fintecture-sdk-javascript#pis-without-connect and https://github.com/Fintecture/fintecture-sdk-javascript#pis-with-connect are not written as far as I can see, not easy to find out what to choose
