### ISSUE TITLE
Impossible to sign a PIS Connect request.

### ISSUE THREAD

**Issue by fburel** [Fintecture/fintecture-sdk-javascript#17]
Hi,

I'm struggling to use the sdk with node 14.15.1.

My private key is stored in a pem file, I read it with fs.read and then pass it along with the appId, and the secret to the client

I manage to get the access tokens, but when it comes to requesting the PIS Connect, I have an error 400

I wrote a little test project here : see a test project here : https://github.com/fburel/fintecture_test

What am I doing wrong?

Thanks.

```
it("should return an url in PIS Connect",function (done) {

        let fClient = null;

        const absolutePath = path.resolve(PRIVATE_KEY);

        fs.readFile(absolutePath, {encoding: "utf-8"})

            .then(key => {
                return new FintectureClient({
                    app_id: APP_ID
                    ,app_secret: SECRET
                    ,private_key: key
                    ,env: ENV
                });
            })

            .then(async client => {

                fClient = client;

                return client.getAccessToken();

            })

            .then(tokens => {
                let connectConfig = {
                    amount: 125,
                    currency: 'EUR',
                    communication: 'Thanks mom!',
                    customer_full_name: 'Bob Smith',
                    customer_email: 'bob.smith@gmail.com',
                    customer_ip: '127.0.0.1',
                    state: 'somestate'
                };

                return fClient.getPisConnect(tokens.access_token, connectConfig);
            })

            .then(tokens => {
                assert.notEqual(tokens.url, undefined);
                done();
            })

            .catch(done)

    });

```

**Comment by hugofintecture** [comment]
Hello @fburel! So sorry for this long delay :/
Have you managed to resolve your issue?

**Comment by hugofintecture** [comment]
Closing the issue for now. Don't hesitate to reopen if needed.

**Comment by arnaudambro** [comment]
@fburel I had the same error
what I did:
- download https://github.com/Fintecture/sample-nodejs
- rename `.env-example` with `.env`
- run `npm i && npm run start:pis-connect`
I saw this was working.
I replaced the `.env` variables with mine: still working

then I could, field by field, see which one was not working on my side.
(maybe `Thanks mom!` ?)
